all:../reg/reg.h ../log/log.h ../log/log.c ../type/type.h  ../conf/conf.h ../conf/conf.cpp ../core/cetty.h ../core/cetty.cpp
	g++ -g -o cetty ../reg/reg.h ../log/log.h ../log/log.c ../type/type.h  ../conf/conf.h ../conf/conf.cpp ../core/cetty.h ../core/cetty.cpp

clean:
	rm -rf cetty
